### PR TITLE
Merge pull request #1 from sy618/master

### PR DESCRIPTION
**Pull request by clion007**
sy618 pull

### CODE REVIEW

**Comment by clion007** [comment]
sy618

**Comment by sy618** [comment]
加一下群
https://t.me/adfqhosts

**Comment by clion007** [comment]
网页打不开呢？

======= 2017-10-11 00:14 00:25 sy618 您在来信中写到: Re: [sy618/hosts] Merge pull request #1 from sy618/master (#62) =======
加一下群
https://t.me/adfqhosts
―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
= = = = = = = = = = = = = = = = = = = =

**Comment by sy618** [comment]
挂代理

**Comment by clion007** [comment]
我没有代理。。。，这个是什么群呢？

**Pull request closed without merging**
